=== braday/kpj/BookApp/web/WEB-INF/books.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="bookshop">
        <xs:complexType>
            <xs:sequence>
                <xs:element type="xs:string" name="name"/>
                <xs:element name="books">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="book" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="title"/>
                                        <xs:element type="xs:string" name="author"/>
                                        <xs:element type="xs:string" name="category"/>
                                        <xs:element type="xs:int" name="qty"/>
                                        <xs:element type="xs:double" name="price"/>
                                        <xs:element name="publication">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element type="xs:string" name="isbn"/>
                                                    <xs:element type="xs:string" name="edition"/>
                                                    <xs:element type="xs:int" name="pubYear"/>
                                                    <xs:element type="xs:string" name="publisher"/>
                                                    <xs:element type="xs:string" name="condition"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute type="xs:int" name="id" use="optional"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== braday/kpj/BookApp/build/web/WEB-INF/books.xml
<?xml version="1.0" encoding="UTF-8"?>
<books xmlns="http://www.uts.edu.au/31284/wsd-books"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://www.uts.edu.au/31284/wsd-books books.xsd">
    <book id="1">
        <title>XML Developer's Guide</title>
        <author>Matthew Gambardella</author>
        <category>Computer</category>
        <qty>1</qty>
        <price>40.0</price>
        <condition>Good</condition>
        <publication>
            <description>a computer book</description>
            <isbn>978-3-16-148410-0</isbn>
            <edition>3rd edition</edition>
            <pubYear>2014</pubYear>
            <publisher>wiley</publisher>
        </publication>
    </book>
    <book id="2">
        <title>Exercise Physiology</title>
        <author>Mcardle</author>
        <category>Health</category>
        <qty>1</qty>
        <price>35.0</price>
        <condition>fair</condition>
        <publication>
            <description>a health book</description>
            <isbn>988-1-70-146450-3</isbn>
            <edition>5th edition</edition>
            <pubYear>2015</pubYear>
            <publisher>wiley</publisher>
        </publication>
    </book>
    <book id="3">
        <title>The New Law of Torts</title>
        <author>Danuta Mendelson</author>
        <category>Legal</category>
        <qty>1</qty>
        <price>55.0</price>
        <condition>fair</condition>
        <publication>
            <description>a law book</description>
            <isbn>988-1-70-146450-3</isbn>
            <edition>7th edition</edition>
            <pubYear>2015</pubYear>
            <publisher>wiley</publisher>
        </publication>
    </book>        
</books>
